package Almox::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Almox::Schema',

    connect_info => {
        dsn => 'dbi:Pg:dbname=almox2',
        user => 'almox',
        password => 'almox',
        AutoCommit => q{1},
        pg_enable_utf8 => 1
    }
);

=head1 NAME

Almox::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Almox>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Almox::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.58

=head1 AUTHOR

sgrs

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
